config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'One', pages_one_path %></li>
          <li><%= link_to 'Two', pages_two_path %></li>
          <li><%= link_to 'Three', pages_three_path %></li>
            </ul>
          </li>
        </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h1>Pages#one</h1>
    <p>Find me in app/views/pages/one.html.erb</p>

    <h1>Marisol Smith Irazábal</h1>
    
  </body>
</html>

app/views/pages/three.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Minion Ipsum</h1>
    <p>Minions ipsum enim incididunt tempor. Gelatooo voluptate tulaliloo aliquip velit poopayee butt underweaaar ullamco eiusmod consectetur. Consequat aute aaaaaah tatata bala tu consectetur. Nisi qui tank yuuu! Cillum irure aute. Officia velit tatata bala tu veniam nostrud hana dul sae laboris veniam occaecat. Duis commodo underweaaar enim para tú sit amet aliqua. Tulaliloo ut ad poopayee gelatooo duis. Tank yuuu! officia gelatooo jiji sit amet.

Pepete ut nostrud belloo! Ad sit amet underweaaar chasy. Pepete ti aamoo! Irure minim jeje potatoooo et et. Me want bananaaa! occaecat la bodaaa poopayee consectetur baboiii ut. Tatata bala tu tempor adipisicing adipisicing ad veniam la bodaaa velit. Daa aliquip poulet tikka masala ut officia. Esse hana dul sae bee do bee do bee do potatoooo tank yuuu!

Nostrud me want bananaaa! Laboris tank yuuu! Occaecat duis aaaaaah labore irure uuuhhh. Ullamco tank yuuu! Quis tank yuuu! Poopayee poulet tikka masala. Enim sed exercitation reprehenderit veniam hahaha bappleees. Reprehenderit butt ullamco cillum ti aamoo! Ut chasy labore nisi ex quis. Dolor hana dul sae duis potatoooo baboiii commodo dolor belloo! Sed reprehenderit. Consectetur uuuhhh aliqua jeje veniam incididunt. Reprehenderit nostrud baboiii hahaha hana dul sae aliqua tulaliloo.</p>

  </body>
</html>

app/views/pages/two.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Pages#two</h1>
    <p>Find me in app/views/pages/two.html.erb</p>
    <%= image_tag "rake.png" %>
  </body>
</html>